Added latest/all for omnibus release paths on travis
aptible/omnibus-aptible-toolbelt pull request #79
Opened 2022-05-16 16:02 UTC by madhuravius

see title. we want to try to have a `latest` deb for ci usages with a direct latest url

---

Current link and expected side by side, but not sure (correct me if I'm mistaken please):

Edited (as in readme after changes):

```
VERSIONED

https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/all/master/340/pkg/aptible-toolbelt_0.19.3%2B20220317192554~debian.9.13-1_amd64.deb

LATEST 

https://omnibus-aptible-toolbelt.s3.amazonaws.com/aptible/omnibus-aptible-toolbelt/latest/aptible-toolbelt-latest_debian.9.13-1_amd64.deb
```

---

1. I checked [this past build](https://api.travis-ci.com/v3/job/564935038/log.txt) and it looks like it uses bash
2. I also tried to adhere to naming i caught in a slack thread

---

Provided some justification for approach in the shell script comment

2022-05-16 17:31 UTC, fancyremarker requested changes

2022-05-16 17:31 UTC, fancyremarker commented on .travis.yml
> +  - [[ "$DOCKER_TAG" = "debian-9" ]] && cp "deploy/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/pkg/aptible-toolbelt*amd64.deb" "deploy/aptible-toolbelt-latest_amd64.deb"
This is roughly correct if we want only to have a latest copy for Debian. (I imagined we'd want it for all platforms, eventually, but this might be good enough to start.)

I think we should decide on how we want both "latest" and all historical artifacts organized in the [omnibus-aptible-toolbelt S3 bucket](https://us-east-1.console.aws.amazon.com/s3/buckets/omnibus-aptible-toolbelt?region=us-east-1&tab=objects), document in the README, and make sure we agree the structure makes sense.

My hunch is it makes more sense to have `latest` and `all` folders at the top-level. The existing artifacts will follow the same-ish nested structure they currently have under `all`, while we can incrementally add new platforms/architectures under `latest`.

2022-05-16 20:59 UTC, madhuravius commented on .travis.yml
> +        - PKG_FILE_EXT=.deb
usage of this is weird, i tried a few alternatives and this ended up seeming the simplest

extracting in bash from generated file is pretty scary/messy:

1. example test on local against a file with `R` prefix (readme.md, and extracting the `.md` out):

<img width="452" alt="image" src="https://user-images.githubusercontent.com/2961973/168681548-a80f6ce2-ad1c-4896-a755-1648d03113ed.png">

2. expanded to usage here would look something like this, which is  unreadable:

```shell
FILE_EXT=${$(ls deploy/${TRAVIS_REPO_SLUG}/all/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/pkg/aptible-toolbelt*)##.*}
```

2022-05-17 15:52 UTC, madhuravius commented on buildscripts/set-latest.sh
> +find "deploy/${TRAVIS_REPO_SLUG}/latest" -name "aptible-toolbelt*" | xargs -I {} bash -c 'rename_file_copy_to_latest "$@"'
this looks to be resolved with latest changes (likely during confusion of multiple xarg examples):

https://app.travis-ci.com/github/aptible/omnibus-aptible-toolbelt/jobs/570489756#L1190

2022-05-17 19:27 UTC, tedivm commented
lgtm but Frank or Ashley should sign off.

2022-05-17 20:47 UTC, almathew commented
Swapped over to @UserNotFound since he can give a better/faster review.

2022-05-18 03:38 UTC, UserNotFound approved these changes
Looks fine to me, but I see a few things that will need follow up changes to account for adding `/all/` in the path:

* [Our homebrew cask for OSX installation](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/aptible.rb)
* [Our PR generate](https://github.com/aptible/toolbelt-auto-update/blob/master/bin/toolbelt-auto-update#L64-L65), which looks for new CLI versions and opens PR's against our public docs and aptible-integration repos
* Update our [windows+OSX package instructions](https://github.com/aptible/scripts/blob/master/doc/ReleaseNewCLIVersion.md), if we're going to do 'latest' with them, too

Nice for the CRE team to do: [community post updates](https://community.aptible.com/t/how-do-i-install-aptible-cli-in-a-docker-image/561) for so that customers can take advantage of the latest, as well as a blog post so it is more widely known by anyone who may benefit.

2022-05-19 18:03 UTC, merged